/**
 * Temario CRUD routes — Fase P1/P2.
 *
 * All write routes are scoped to the authenticated user: a route never mutates
 * a subject/temario/tema/hito the caller does not own. Stars and `status=done`
 * on a Tema are NOT exposed through these client-write routes (P0-3).
 *
 * P2 additions:
 * - POST /:subjectId/temario:generate — runs the agentic temario-builder over
 *   a Fuente's extracted text.
 * - Editing a temario that was generated by AI flips generatedBy to "ai-edited".
 */
import { Hono } from "hono";
import { z } from "zod";
import { eq } from "drizzle-orm";
import type { AppDeps } from "../deps";
import type { AuthVariables } from "../auth/middleware";
import { errorResponse } from "../errors";
import { findSubjectById } from "../repositories/subjects";
import { findFuenteById } from "../repositories/fuentes";
import { findUserById } from "../repositories/users";
import { hitos, temas } from "../db/schema";
import type { Temario, TemarioGeneratedBy } from "@buxo/domain/temario";
import { projectTemarioVisibility, projectTemasVisibility } from "@buxo/domain/temario";
import { seedAttributionFor, seedSourceLangFor } from "@buxo/domain/seed-catalog";
import {
  buildTemarioBuilderSystemPrompt,
  buildTemarioBuilderUserPrompt,
  PROMPT_VERSION as TEMARIO_BUILDER_PROMPT_VERSION,
  PROMPT_VERSION_EN as TEMARIO_BUILDER_PROMPT_VERSION_EN,
} from "@buxo/models/prompts/temario-builder-prompt";
import { normalizePreferredLanguageCode } from "../locale";
import { TEMARIO_TOOLS } from "../models/tools/temario-tools";
import type { AnyToolDefinition, ServerToolContext } from "../models/tools/types";
import { recordTemarioBuilderUsage } from "../quota/enforce";
import {
  createMilestoneInTemario,
  createTemario,
  createTopicInTemario,
  deleteMilestoneFromTemario,
  deleteTopicFromTemario,
  findTemarioById,
  findTemarioBySubject,
  reorderTopicsInTemario,
  setRecommendedTopic,
  updateMilestoneInTemario,
  updateTemarioGeneratedBy,
  updateTopicInTemario,
} from "../repositories/temarios";

const TopicTitleSchema = z.string().min(1).max(60);

const CreateTopicSchema = z.object({
  title: TopicTitleSchema,
  order: z.number().int().min(0).optional(),
});

const UpdateTopicSchema = z.object({
  title: TopicTitleSchema.optional(),
  order: z.number().int().min(0).optional(),
  recommended: z.boolean().optional(),
});

const ReorderTopicsSchema = z.object({
  orderedIds: z.array(z.string().min(1)).min(1),
});

const CreateMilestoneSchema = z.object({
  kind: z.enum(["parcial", "examen_final"]),
  title: TopicTitleSchema,
  coversUpToOrder: z.number().int().min(0),
  order: z.number().int().min(0).optional(),
});

const UpdateMilestoneSchema = z.object({
  title: TopicTitleSchema.optional(),
  order: z.number().int().min(0).optional(),
  coversUpToOrder: z.number().int().min(0).optional(),
});

const GenerateTemarioSchema = z.object({
  fuenteId: z.string().min(1),
});

async function loadSubjectAndCheckOwnership(db: AppDeps["db"], userId: string, subjectId: string) {
  const subject = await findSubjectById(db, subjectId);
  if (!subject || subject.userId !== userId) return null;
  return subject;
}

async function topicAndTemario(db: AppDeps["db"], topicId: string) {
  const [tema] = await db.select().from(temas).where(eq(temas.id, topicId)).limit(1);
  if (!tema) return null;
  const temario = await findTemarioById(db, tema.temarioId);
  return temario ? { tema, temario } : null;
}

async function milestoneAndTemario(db: AppDeps["db"], milestoneId: string) {
  const [hito] = await db.select().from(hitos).where(eq(hitos.id, milestoneId)).limit(1);
  if (!hito) return null;
  const temario = await findTemarioById(db, hito.temarioId);
  return temario ? { hito, temario } : null;
}

async function maybeMarkAiEdited(db: AppDeps["db"], temario: Temario | null) {
  if (temario && temario.generatedBy === "ai") {
    await updateTemarioGeneratedBy(db, temario.id, "ai-edited");
  }
}

export function createTemarioRoutes(deps: AppDeps): Hono<{ Variables: AuthVariables }> {
  const app = new Hono<{ Variables: AuthVariables }>();

  app.get("/:subjectId", async (c) => {
    const userId = c.get("userId");
    const subject = await loadSubjectAndCheckOwnership(deps.db, userId, c.req.param("subjectId"));
    if (!subject) return errorResponse(c, "not_found", "Subject not found");

    const temario = await findTemarioBySubject(deps.db, subject.id);
    if (!temario) return errorResponse(c, "not_found", "Temario not found");
    // P4 antifuga: `Tema.stars` is denormalized on the topic row (see
    // temario.ts's docblock on `projectTemarioVisibility`) — gate it the
    // same way routes/mastery.ts and routes/xp.ts gate their own payloads.
    // Plan-xp-progreso Fase 2: also include `visibility` so the client can
    // distinguish "no dato" (shadow → hide) from "dato es cero" (visible).
    const projected = projectTemarioVisibility(temario, deps.env.MASTERY_VISIBILITY_MODE);
    // C2-d: the CC BY attribution line the client needs at the foot of the
    // temario screen — colgado de esta MISMA respuesta (no endpoint nuevo)
    // porque `subject` ya está en memoria acá con exactamente los dos datos
    // que hacen falta (`seedCatalogKey`/`seedLang`, congelados en la
    // activación del seed, C1-b). `seedCatalogKey` viaja también tal cual
    // para que el cliente derive el nivel (bachillerato/universidad) del
    // caption de cabecera sin un tercer campo derivado a mano acá.
    //
    // C2-e adds `seedMaterialLang` (`seedSourceLangFor`, mismo resolver
    // interno que `seedAttributionFor`): el idioma del libro detrás del
    // temario, que puede DIVERGIR del idioma de la UI — `Subject.seedLang`
    // se congela desde `users.preferredLanguageCode` sin mirar las fuentes
    // (C2-a), así que un usuario `es` con `bachillerato/fisica` (única
    // fuente EN-only) estudia el temario en español respaldado por un libro
    // en inglés; el cliente usa esto para la nota "Material en inglés" en
    // la card de home. Sigue en esta MISMA respuesta, sin endpoint nuevo.
    const seedLang: "en" | "es" = subject.seedLang === "en" ? "en" : "es";
    const seedAttribution = subject.seedCatalogKey ? seedAttributionFor(subject.seedCatalogKey, seedLang) : null;
    const seedMaterialLang = subject.seedCatalogKey ? seedSourceLangFor(subject.seedCatalogKey, seedLang) : null;
    return c.json({
      ...projected,
      visibility: deps.env.MASTERY_VISIBILITY_MODE,
      seedCatalogKey: subject.seedCatalogKey,
      seedAttribution,
      seedMaterialLang,
    });
  });

  app.post("/:subjectId", async (c) => {
    const userId = c.get("userId");
    const subject = await loadSubjectAndCheckOwnership(deps.db, userId, c.req.param("subjectId"));
    if (!subject) return errorResponse(c, "not_found", "Subject not found");

    const existing = await findTemarioBySubject(deps.db, subject.id);
    if (existing) return errorResponse(c, "conflict", "Subject already has a temario");

    const temario = await createTemario(deps.db, { userId, subjectId: subject.id, generatedBy: "manual" });
    return c.json(temario, 201);
  });

  app.post("/:subjectId/temario:generate", async (c) => {
    const userId = c.get("userId");
    const subject = await loadSubjectAndCheckOwnership(deps.db, userId, c.req.param("subjectId"));
    if (!subject) return errorResponse(c, "not_found", "Subject not found");

    const parsed = GenerateTemarioSchema.safeParse(await c.req.json().catch(() => null));
    if (!parsed.success) return errorResponse(c, "invalid_request", parsed.error.message);

    const fuente = await findFuenteById(deps.db, parsed.data.fuenteId);
    if (!fuente || fuente.userId !== userId || fuente.subjectId !== subject.id) {
      return errorResponse(c, "not_found", "Fuente not found");
    }

    // P2 FIX4 (2026-07-21 post-real-run REVIEW): do NOT flip `generatedBy`
    // to "ai" before the builder runs. The real Haiku run left a temario
    // marked "ai" with a client-visible 500 (the crash happened AFTER the
    // flip but the client never saw the flip succeed) — a half-built
    // temario silently badged as AI-complete. Instead: create a brand-new
    // temario as "manual" (its honest state until proven otherwise) and
    // remember whatever `generatedBy` an EXISTING temario already had, so a
    // failure can restore exactly that value instead of guessing.
    let temario = await findTemarioBySubject(deps.db, subject.id);
    const previousGeneratedBy: TemarioGeneratedBy = temario?.generatedBy ?? "manual";
    if (!temario) {
      temario = await createTemario(deps.db, { userId, subjectId: subject.id, generatedBy: "manual" });
    }

    // Slice localización (A3b s5/AJUSTE 4): la preferred language del
    // estudiante decide la variante del builder. SOLO "en" pasa la opción —
    // "es" (el default de toda la base instalada) conserva el template
    // español byte-idéntico y la versión default. El usuario se carga una
    // vez y se reusa abajo para el registro de costo (FIX5).
    const user = await findUserById(deps.db, userId);
    const locale = normalizePreferredLanguageCode(user?.preferredLanguageCode);
    const localeOption = locale === "en" ? ("en" as const) : undefined;

    const toolContext: ServerToolContext = { db: deps.db, userId, subjectId: subject.id };
    const system = localeOption
      ? buildTemarioBuilderSystemPrompt(subject.name, localeOption)
      : buildTemarioBuilderSystemPrompt(subject.name);
    const prompt = buildTemarioBuilderUserPrompt({
      sourceText: fuente.text,
      subjectName: subject.name,
      ...(localeOption ? { locale: localeOption } : {}),
    });

    let result: Awaited<ReturnType<typeof deps.models.temarioBuilderAdapter.generateTemario>>;
    try {
      result = await deps.models.temarioBuilderAdapter.generateTemario({
        system,
        prompt,
        tools: TEMARIO_TOOLS as unknown as ReadonlyArray<AnyToolDefinition<unknown>>,
        toolContext,
        subjectId: subject.id,
        promptVersion: localeOption ? TEMARIO_BUILDER_PROMPT_VERSION_EN : TEMARIO_BUILDER_PROMPT_VERSION,
      });
    } catch (err) {
      // FIX4 (decision): topics/milestones the tools already committed
      // before the failure are KEPT, not rolled back — FIX2's idempotent
      // dedup-by-title means a retried generation will skip them rather
      // than duplicate them, so nothing is lost by leaving them in place.
      // `generatedBy` is reverted to its pre-call value so a client reading
      // the temario after this 500 sees an honest, non-"ai" state instead
      // of a half-built temario claiming to be AI-complete.
      await updateTemarioGeneratedBy(deps.db, temario.id, previousGeneratedBy);
      console.error("[temario:generate] builder failed", err instanceof Error ? err.message : String(err));
      return errorResponse(c, "internal_error", "Temario generation failed; no changes were marked as AI-generated.");
    }

    // Only on success does the temario get badged "ai".
    await updateTemarioGeneratedBy(deps.db, temario.id, "ai");

    // P2 FIX5: durable cost recording — the temario-builder used to run
    // behind a `NoopTelemetrySink` with nowhere durable for its cost to
    // land, even on success. Record it into the same `usage_quotas` rows
    // every other task's cost accumulates into (see quota/enforce.ts).
    // (El usuario ya se cargó arriba para resolver la locale — un solo
    // findUserById por request.)
    if (user) {
      await recordTemarioBuilderUsage(deps.db, userId, user.accountKind, deps.quotaConfig, result.costUsd, deps.now());
    }

    temario = await findTemarioBySubject(deps.db, subject.id);
    const projected = temario ? projectTemarioVisibility(temario, deps.env.MASTERY_VISIBILITY_MODE) : temario;
    return c.json({ temario: projected, generatedBy: temario?.generatedBy, result });
  });

  app.post("/:subjectId/topics", async (c) => {
    const userId = c.get("userId");
    const subject = await loadSubjectAndCheckOwnership(deps.db, userId, c.req.param("subjectId"));
    if (!subject) return errorResponse(c, "not_found", "Subject not found");

    let temario = await findTemarioBySubject(deps.db, subject.id);
    if (!temario) {
      temario = await createTemario(deps.db, { userId, subjectId: subject.id, generatedBy: "manual" });
    }

    const parsed = CreateTopicSchema.safeParse(await c.req.json().catch(() => null));
    if (!parsed.success) return errorResponse(c, "invalid_request", parsed.error.message);

    const topic = await createTopicInTemario(deps.db, {
      temarioId: temario.id,
      title: parsed.data.title,
      order: parsed.data.order,
    });
    await maybeMarkAiEdited(deps.db, temario);
    return c.json(topic, 201);
  });

  app.patch("/topics/:topicId", async (c) => {
    const userId = c.get("userId");
    const parsed = UpdateTopicSchema.safeParse(await c.req.json().catch(() => null));
    if (!parsed.success) return errorResponse(c, "invalid_request", parsed.error.message);

    const pair = await topicAndTemario(deps.db, c.req.param("topicId"));
    if (!pair || pair.temario.userId !== userId) return errorResponse(c, "not_found", "Topic not found");

    if (parsed.data.recommended) {
      await setRecommendedTopic(deps.db, pair.temario.id, c.req.param("topicId"));
    }

    const topic = await updateTopicInTemario(deps.db, {
      id: c.req.param("topicId"),
      title: parsed.data.title,
      order: parsed.data.order,
      recommended: parsed.data.recommended,
    });
    await maybeMarkAiEdited(deps.db, pair.temario);
    return c.json(topic);
  });

  app.delete("/topics/:topicId", async (c) => {
    const userId = c.get("userId");
    const pair = await topicAndTemario(deps.db, c.req.param("topicId"));
    if (!pair || pair.temario.userId !== userId) return errorResponse(c, "not_found", "Topic not found");

    await deleteTopicFromTemario(deps.db, c.req.param("topicId"));
    await maybeMarkAiEdited(deps.db, pair.temario);
    return c.body(null, 204);
  });

  app.post("/:subjectId/topics/reorder", async (c) => {
    const userId = c.get("userId");
    const subject = await loadSubjectAndCheckOwnership(deps.db, userId, c.req.param("subjectId"));
    if (!subject) return errorResponse(c, "not_found", "Subject not found");

    const temario = await findTemarioBySubject(deps.db, subject.id);
    if (!temario) return errorResponse(c, "not_found", "Temario not found");

    const parsed = ReorderTopicsSchema.safeParse(await c.req.json().catch(() => null));
    if (!parsed.success) return errorResponse(c, "invalid_request", parsed.error.message);

    const reordered = await reorderTopicsInTemario(deps.db, temario.id, parsed.data.orderedIds);
    await maybeMarkAiEdited(deps.db, temario);
    return c.json(projectTemasVisibility(reordered, deps.env.MASTERY_VISIBILITY_MODE));
  });

  app.post("/:subjectId/milestones", async (c) => {
    const userId = c.get("userId");
    const subject = await loadSubjectAndCheckOwnership(deps.db, userId, c.req.param("subjectId"));
    if (!subject) return errorResponse(c, "not_found", "Subject not found");

    let temario = await findTemarioBySubject(deps.db, subject.id);
    if (!temario) {
      temario = await createTemario(deps.db, { userId, subjectId: subject.id, generatedBy: "manual" });
    }

    const parsed = CreateMilestoneSchema.safeParse(await c.req.json().catch(() => null));
    if (!parsed.success) return errorResponse(c, "invalid_request", parsed.error.message);

    const milestone = await createMilestoneInTemario(deps.db, {
      temarioId: temario.id,
      kind: parsed.data.kind,
      title: parsed.data.title,
      coversUpToOrder: parsed.data.coversUpToOrder,
      order: parsed.data.order,
    });
    await maybeMarkAiEdited(deps.db, temario);
    return c.json(milestone, 201);
  });

  app.patch("/milestones/:milestoneId", async (c) => {
    const userId = c.get("userId");
    const pair = await milestoneAndTemario(deps.db, c.req.param("milestoneId"));
    if (!pair || pair.temario.userId !== userId) return errorResponse(c, "not_found", "Milestone not found");

    const parsed = UpdateMilestoneSchema.safeParse(await c.req.json().catch(() => null));
    if (!parsed.success) return errorResponse(c, "invalid_request", parsed.error.message);

    const milestone = await updateMilestoneInTemario(deps.db, {
      id: c.req.param("milestoneId"),
      title: parsed.data.title,
      order: parsed.data.order,
      coversUpToOrder: parsed.data.coversUpToOrder,
    });
    await maybeMarkAiEdited(deps.db, pair.temario);
    return c.json(milestone);
  });

  app.delete("/milestones/:milestoneId", async (c) => {
    const userId = c.get("userId");
    const pair = await milestoneAndTemario(deps.db, c.req.param("milestoneId"));
    if (!pair || pair.temario.userId !== userId) return errorResponse(c, "not_found", "Milestone not found");

    await deleteMilestoneFromTemario(deps.db, c.req.param("milestoneId"));
    await maybeMarkAiEdited(deps.db, pair.temario);
    return c.body(null, 204);
  });

  app.patch("/:subjectId/generated-by", async (c) => {
    const userId = c.get("userId");
    const subject = await loadSubjectAndCheckOwnership(deps.db, userId, c.req.param("subjectId"));
    if (!subject) return errorResponse(c, "not_found", "Subject not found");

    const body = z
      .object({ generatedBy: z.enum(["manual", "ai", "ai-edited"]) })
      .safeParse(await c.req.json().catch(() => null));
    if (!body.success) return errorResponse(c, "invalid_request", body.error.message);

    const temario = await findTemarioBySubject(deps.db, subject.id);
    if (!temario) return errorResponse(c, "not_found", "Temario not found");

    const updated = await updateTemarioGeneratedBy(deps.db, temario.id, body.data.generatedBy);
    if (!updated) return errorResponse(c, "not_found", "Temario not found");
    return c.json(updated);
  });

  return app;
}
