/**
 * SPIKE F0.5 (ingestion memory gate) — dev screen.
 *
 * THROWAWAY, __DEV__-ONLY, per
 * docs/plan-app-multiplataforma/especificaciones/C-cliente-e-ingesta.md §2
 * and the architect ruling for this run: lives inside the real app so the
 * gate runs under the app's real memory footprint (~409MB PSS baseline,
 * see docs/plan-app-multiplataforma/reports/wp6-verificacion.md) — the
 * honest F2 scenario, not a bare-bones throwaway shell.
 *
 * REMOVAL: delete this file, `spike-f05/`, and `lib/spikeF05Bridge.ts` (+
 * its test), and the dev-only link in `app/login.tsx`
 * ("SPIKE_F05_DEV_LINK_START/END" markers). Nothing else in the app
 * imports any of this — it is not reachable in a production build because
 * (a) the link to this screen only renders when `__DEV__` is true, and
 * (b) this component itself renders a plain message and returns early when
 * `__DEV__` is false, as a second independent guard.
 *
 * Loads `docs/guia1.pdf` (+ optional secondary PDFs, §2.3) — embedded as
 * base64 by `spike-f05/build.mjs` into the gitignored
 * `spike-f05/generated/spike-webview.generated.ts` — into a hidden
 * WebView running the REUSED (unmodified) `lib/pdf/` pipeline
 * (`parsePdf` -> `classifyPage`/`DEFAULT_THRESHOLDS` -> `ingestPdfTiered`)
 * from `apps/harness`, with `transcribe` mocked (canned text + artificial
 * delay, zero real API calls — spec §0 point 4).
 *
 * Results are shown in a plain-text panel AND dumped to logcat (chunked,
 * `F05_SPIKE_RESULT i/total <json-fragment>` lines) so they can be pulled
 * off-device with `adb logcat -d | grep F05_SPIKE_RESULT` even if the
 * on-screen panel scrolls off / the app is later killed by the OOM killer
 * mid-run (the scenario §2.5 explicitly gates on).
 */
import { useMemo, useRef, useState } from "react";
import { ScrollView, Text, View } from "react-native";
import { WebView, type WebViewMessageEvent } from "react-native-webview";

import { useTheme } from "../../theme/useTheme";
import { spacing, typography } from "../../theme/tokens";
import { PrimaryButton } from "../../components/PrimaryButton";
import {
  chunkForLogcat,
  parseWebToHostMessage,
  type SpikeResult,
  type WebToHostMessage,
} from "../../lib/spikeF05Bridge";

// Generated by `node spike-f05/build.mjs` (gitignored — see that file's
// docblock). Run the build script before starting Metro; if you see a
// "Cannot find module" error here, that's why.
// eslint-disable-next-line import/no-unresolved -- generated file, see above
import {
  SPIKE_BASE_URL,
  SPIKE_BUILD_INFO,
  SPIKE_PDF_MANIFEST,
  SPIKE_WEBVIEW_HTML,
} from "../../spike-f05/generated/spike-webview.generated";

interface LogLine {
  ts: number;
  text: string;
}

export default function SpikeF05Screen() {
  if (!__DEV__) {
    // Second, independent guard beyond the login-screen link's __DEV__
    // check — this screen renders nothing useful outside dev builds.
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>SPIKE F0.5 is a __DEV__-only screen.</Text>
      </View>
    );
  }
  return <SpikeF05Dev />;
}

function SpikeF05Dev() {
  const { colors } = useTheme();
  const webviewRef = useRef<WebView>(null);
  const [running, setRunning] = useState<string | null>(null); // fileName currently running, or null
  const [lines, setLines] = useState<LogLine[]>([]);
  const [result, setResult] = useState<SpikeResult | null>(null);
  const [rnStartedAt, setRnStartedAt] = useState<number | null>(null);

  const pdfNames = useMemo(() => Object.keys(SPIKE_PDF_MANIFEST), []);

  function appendLine(text: string) {
    setLines((prev) => [...prev.slice(-300), { ts: Date.now(), text }]);
  }

  function dumpResultToLogcat(r: SpikeResult) {
    const payload = JSON.stringify(r);
    const chunks = chunkForLogcat(payload);
    // eslint-disable-next-line no-console -- deliberate: this IS the
    // off-device evidence-extraction mechanism (adb logcat -d | grep
    // F05_SPIKE_RESULT), per the architect's Phase 1 instructions.
    console.log(`F05_SPIKE_RESULT_BEGIN fileName=${r.fileName} chunks=${chunks.length}`);
    for (const c of chunks) console.log(c);
    // eslint-disable-next-line no-console
    console.log("F05_SPIKE_RESULT_END");
  }

  function runPdf(fileName: string) {
    const base64 = SPIKE_PDF_MANIFEST[fileName];
    if (!base64) {
      appendLine(`ERROR: ${fileName} not embedded in this build (see spike-f05/build.mjs output).`);
      return;
    }
    setRunning(fileName);
    setResult(null);
    setLines([]);
    setRnStartedAt(Date.now());
    appendLine(`Cargando ${fileName} (${Math.round((base64.length * 3) / 4 / 1024)} KB) -> WebView...`);
    webviewRef.current?.postMessage(JSON.stringify({ type: "run", fileName, pdfBase64: base64 }));
  }

  function handleMessage(event: WebViewMessageEvent) {
    const msg: WebToHostMessage | null = parseWebToHostMessage(event.nativeEvent.data);
    if (!msg) {
      appendLine(`WARN: mensaje del WebView no reconocido (bridge shape) — dump crudo: ${event.nativeEvent.data.slice(0, 200)}`);
      return;
    }
    switch (msg.type) {
      case "log":
        appendLine(`[web:${msg.level}] ${msg.message}`);
        break;
      case "progress":
        appendLine(`progreso: página ${msg.page}/${msg.total} -> route.kind = ${msg.routeKind}`);
        break;
      case "fatal":
        appendLine(`FATAL: ${msg.message}`);
        setRunning(null);
        break;
      case "result": {
        const rnElapsedMs = rnStartedAt ? Date.now() - rnStartedAt : null;
        appendLine(
          `RESULTADO: elapsed(WebView)=${msg.result.totalElapsedMs.toFixed(0)}ms elapsed(RN wall)=${rnElapsedMs ?? "?"}ms páginas=${msg.result.routes.length} errores-no-manejados=${msg.result.unhandledErrors.length}`,
        );
        setResult(msg.result);
        setRunning(null);
        dumpResultToLogcat(msg.result);
        break;
      }
    }
  }

  return (
    <ScrollView
      style={{ flex: 1, backgroundColor: colors.surface }}
      contentContainerStyle={{ padding: spacing.lg, gap: spacing.md }}
    >
      <Text style={{ color: colors.accent, fontSize: typography.heading.fontSize, fontWeight: typography.weights.bold }}>
        SPIKE F0.5 — gate de ingesta (WebView-bridge)
      </Text>
      <Text style={{ color: colors.muted, fontSize: typography.small.fontSize }}>
        THROWAWAY / __DEV__ only. Ver especificaciones/C-cliente-e-ingesta.md §2.
        {"\n"}Build: {SPIKE_BUILD_INFO.builtAt} · worker bundle {Math.round(SPIKE_BUILD_INFO.workerBundleBytes / 1024)}KB · main bundle {Math.round(SPIKE_BUILD_INFO.mainBundleBytes / 1024)}KB
      </Text>

      <View style={{ gap: spacing.sm }}>
        {pdfNames.map((name) => (
          <PrimaryButton
            key={name}
            label={running === name ? `Cargando ${name}...` : `Cargar ${name}`}
            onPress={() => runPdf(name)}
            disabled={running !== null}
          />
        ))}
      </View>

      <Text style={{ color: colors.foreground, fontSize: typography.small.fontSize, fontWeight: typography.weights.semibold }}>
        Log (más reciente al final) — también volcado a logcat, prefijo F05_SPIKE_RESULT:
      </Text>
      <View
        style={{
          backgroundColor: colors.surfaceRaised,
          borderColor: colors.border,
          borderWidth: 1,
          borderRadius: 8,
          padding: spacing.sm,
          maxHeight: 260,
        }}
      >
        <ScrollView nestedScrollEnabled>
          {lines.map((l, i) => (
            <Text key={i} style={{ color: colors.foreground, fontSize: 10, fontFamily: "monospace" }}>
              {new Date(l.ts).toISOString().slice(11, 23)} {l.text}
            </Text>
          ))}
        </ScrollView>
      </View>

      {result ? <ResultPanel result={result} /> : null}

      {/* Hidden-ish WebView: given a real size (0x0 can cause some WebView
          implementations to throttle/never render, which would invalidate
          the memory-under-rasterization measurement) but visually tucked
          out of the way. NOT display:none for the same reason. */}
      <View style={{ height: 1, overflow: "hidden" }}>
        <WebView
          ref={webviewRef}
          originWhitelist={["*"]}
          source={{ html: SPIKE_WEBVIEW_HTML, baseUrl: SPIKE_BASE_URL }}
          style={{ width: 300, height: 300 }}
          javaScriptEnabled
          domStorageEnabled
          onMessage={handleMessage}
          onError={(e) => appendLine(`WebView onError: ${JSON.stringify(e.nativeEvent)}`)}
          onHttpError={(e) => appendLine(`WebView onHttpError: ${JSON.stringify(e.nativeEvent)}`)}
          onRenderProcessGone={(e) => appendLine(`WebView onRenderProcessGone (OOM/crash signal!): ${JSON.stringify(e.nativeEvent)}`)}
        />
      </View>
    </ScrollView>
  );
}

function ResultPanel(props: { result: SpikeResult }) {
  const { colors } = useTheme();
  const r = props.result;
  const tier0Preview = r.materialText.slice(0, 4000);
  return (
    <View style={{ gap: spacing.sm }}>
      <Text style={{ color: colors.foreground, fontSize: typography.small.fontSize, fontWeight: typography.weights.semibold }}>
        Resultado — {r.fileName}
      </Text>
      <MonoBlock
        label="Rutas por página (route.kind)"
        text={r.routes.map((x) => `página ${x.page}/${x.total}: ${x.routeKind}`).join("\n")}
      />
      <MonoBlock
        label="Reporte (ProcessingReport)"
        text={r.report.map((x) => `p${x.page} route=${x.route} cost=${x.costUsd} cached=${x.cached}`).join("\n")}
      />
      <MonoBlock
        label="Blobs cloud-tier (validación PNG)"
        text={
          r.blobDiagnostics.length === 0
            ? "(ninguno — todas las páginas fueron local-text)"
            : r.blobDiagnostics.map((b) => `mode=${b.mode} bytes=${b.sizeBytes} pngValid=${b.pngMagicValid}`).join("\n")
        }
      />
      <MonoBlock
        label="Worker diagnostics (re-check Math.sumPrecise / worker TypeError)"
        text={JSON.stringify(r.workerDiagnostics, null, 2)}
      />
      <MonoBlock
        label={`Errores no manejados (${r.unhandledErrors.length})`}
        text={r.unhandledErrors.length === 0 ? "(ninguno)" : r.unhandledErrors.map((e) => `${e.message}\n${e.stack ?? ""}`).join("\n---\n")}
      />
      <MonoBlock
        label={`Console events (${r.consoleEvents.length}) — warn/error primero`}
        text={r.consoleEvents
          .filter((e) => e.level === "warn" || e.level === "error")
          .map((e) => `[${e.level}] ${e.message}`)
          .join("\n") || "(sin warnings/errors)"}
      />
      <MonoBlock label="Texto Tier-0 extraído (material assembled, primeros 4000 chars — cloud marcado con ⟦F05-MOCK-CLOUD⟧)" text={tier0Preview} />
    </View>
  );
}

function MonoBlock(props: { label: string; text: string }) {
  const { colors } = useTheme();
  return (
    <View style={{ gap: 4 }}>
      <Text style={{ color: colors.muted, fontSize: typography.caption.fontSize }}>{props.label}</Text>
      <View style={{ backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderWidth: 1, borderRadius: 8, padding: spacing.sm }}>
        <Text selectable style={{ color: colors.foreground, fontSize: 10, fontFamily: "monospace" }}>
          {props.text}
        </Text>
      </View>
    </View>
  );
}
