#!/usr/bin/env node
/**
 * Material ingest WebView bundle — build script (F2 WQ2 Part 2), promoted
 * from `spike-f05/build.mjs`'s pattern (see that file's docblock for the
 * full "why generated, why gitignored" reasoning — same answers apply
 * here, condensed below).
 *
 * Run manually — `node materials/build.mjs` from `apps/mobile`, or `npm
 * run build:materials-webview` — before starting Metro / running
 * `expo run:android` / `expo export`, and again any time
 * `webview-src/entry.ts` changes. UNLIKE the spike, this is PRODUCTION
 * code (no PDF is embedded at build time — the student picks an arbitrary
 * PDF at runtime via `expo-document-picker`, bytes cross the bridge live)
 * — the F2 WQ2 Part 3 on-device rebuild MUST run this first.
 *
 * What this does:
 * 1. esbuild-bundles `apps/harness/lib/pdf/worker-entry.ts` (unmodified) —
 *    the real pdf.js worker + Math.sumPrecise polyfill — to a
 *    self-contained ESM string, spawned later from a `blob:` URL (see
 *    `webview-src/entry.ts`'s Worker-patch docblock).
 * 2. esbuild-bundles `webview-src/entry.ts` (parse+classify+split driver),
 *    injecting (1)'s text via esbuild `define` as `__WORKER_BUNDLE_SOURCE__`.
 * 3. Wraps (2) in a minimal HTML document and writes it to
 *    `generated/material-ingest-webview.generated.ts` as a plain JS string
 *    literal, imported by `components/MaterialIngestBar.tsx`.
 *
 * Gitignored: same reasoning as the spike's generated output — it's a
 * ~3-4MB deterministic build artifact of checked-in source, regenerated
 * locally/in CI before any Metro bundle or native build.
 */
import { build } from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const mobileRoot = path.resolve(__dirname, ".."); // apps/mobile
const appsRoot = path.resolve(mobileRoot, ".."); // apps
const repoRoot = path.resolve(appsRoot, ".."); // repo root
const harnessPdfDir = path.join(appsRoot, "harness", "lib", "pdf");
const generatedDir = path.join(__dirname, "generated");

const MATERIAL_INGEST_BASE_URL = "https://buxo-material-ingest.local/";

async function bundleToText(entryPoint, extraOptions = {}) {
  const result = await build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2020",
    write: false,
    absWorkingDir: repoRoot,
    logLevel: "warning",
    ...extraOptions,
  });
  const out = result.outputFiles?.find((f) => f.path.endsWith(".js")) ?? result.outputFiles?.[0];
  if (!out) throw new Error(`build.mjs: esbuild produced no output for ${entryPoint}`);
  return out.text;
}

/** Defends against the bundled JS containing a literal `</script` substring, which would prematurely close our inline `<script>` tag when the WebView parses this as HTML. */
function escapeScriptClose(js) {
  return js.replace(/<\/script/gi, "<\\/script");
}

function buildHtmlDocument(mainBundleJs) {
  const safeJs = escapeScriptClose(mainBundleJs);
  // Deliberately minimal: no CSS frameworks, no external resources, zero
  // network fetches (baseUrl exists only so relative `new URL(...)`
  // construction inside lib/pdf/parse.ts doesn't throw — nothing is ever
  // actually fetched from it, per the Worker patch in webview-src/entry.ts).
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>socrates material ingest (hidden WebView)</title>
</head>
<body>
<script type="module">
${safeJs}
</script>
</body>
</html>`;
}

async function main() {
  console.log("materials/build.mjs: bundling worker-entry.ts (real pdf.js worker + Math.sumPrecise polyfill)...");
  const workerEntryPath = path.join(harnessPdfDir, "worker-entry.ts");
  const workerBundleText = await bundleToText(workerEntryPath);
  console.log(`  -> ${(workerBundleText.length / 1024).toFixed(1)} KB`);

  console.log("materials/build.mjs: bundling webview-src/entry.ts (parse+classify+split driver + bridge)...");
  const entryPath = path.join(__dirname, "webview-src", "entry.ts");
  const mainBundleText = await bundleToText(entryPath, {
    define: { __WORKER_BUNDLE_SOURCE__: JSON.stringify(workerBundleText) },
  });
  console.log(`  -> ${(mainBundleText.length / 1024).toFixed(1)} KB`);

  const html = buildHtmlDocument(mainBundleText);

  mkdirSync(generatedDir, { recursive: true });
  const outPath = path.join(generatedDir, "material-ingest-webview.generated.ts");
  const contents = `/**
 * AUTO-GENERATED by materials/build.mjs — DO NOT EDIT BY HAND.
 * Regenerate: \`node materials/build.mjs\` from apps/mobile (or \`npm run
 * build:materials-webview\`). Gitignored — see build.mjs docblock.
 *
 * Built at: ${new Date().toISOString()}
 */
export const MATERIAL_INGEST_BASE_URL = ${JSON.stringify(MATERIAL_INGEST_BASE_URL)};
export const MATERIAL_INGEST_WEBVIEW_HTML = ${JSON.stringify(html)};
export const MATERIAL_INGEST_BUILD_INFO = ${JSON.stringify(
    { builtAt: new Date().toISOString(), workerBundleBytes: workerBundleText.length, mainBundleBytes: mainBundleText.length },
    null,
    2,
  )};
`;
  writeFileSync(outPath, contents, "utf8");
  console.log(`materials/build.mjs: wrote ${outPath} (${(contents.length / 1024).toFixed(1)} KB total)`);
}

main().catch((err) => {
  console.error("materials/build.mjs FAILED:", err);
  process.exit(1);
});
