// @ts-check
/* eslint-disable @typescript-eslint/no-require-imports -- Expo config plugins are CommonJS by contract (run directly under Node during `expo prebuild`, no bundler) */
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('@expo/config-plugins');

/**
 * Config plugin: regenerates the `release` build-type source-set override
 * that lets a `release`-signed APK talk to the LOCAL QA harness over
 * cleartext HTTP, scoped ONLY to loopback hosts. QA-only, default OFF —
 * gated by the `BUXO_QA_CLEARTEXT` env var (see `isQaCleartextEnabled`
 * below). Never set it when building for students.
 *
 * WHY THIS EXISTS (device-e13 plan, docs/plan-device-e13/00-plan.md, M0/M2 —
 * carried over verbatim from the original hand-written files, which lived
 * only under the gitignored `apps/mobile/android/` and were erased by
 * `expo prebuild --clean`):
 *
 * The M2 performance gate must be measured on a release-like build
 * (debug/reanimated is dramatically slower and would give a false
 * negative), but API 33 blocks cleartext HTTP by default in `release`, and
 * the release build needs to talk to the LOCAL harness
 * (harness/web-local/, BUXO_FAKE_MODELS=1) at http://localhost:3001 via
 * `adb reverse tcp:3001 tcp:3001`.
 *
 * The network security config allows cleartext ONLY to loopback addresses
 * (10.0.2.2 is the Android emulator's alias for the host loopback;
 * 127.0.0.1/localhost is the device's own loopback, which is what `adb
 * reverse` maps to). It does NOT enable cleartext globally — any other
 * host still requires HTTPS, same as stock release behavior. Scoped to the
 * `release` build type only (`app/src/release/`, its own source set) —
 * `debug`/`debugOptimized` use their own manifest's
 * `usesCleartextTraffic=true` (RN Gradle plugin default, unrelated to this
 * file) and never load this config.
 *
 * This must never ship in a real production release to end users under the
 * beta signing key on Render prod — that's exactly why it's gated behind
 * `BUXO_QA_CLEARTEXT` and OFF by default, instead of being generated
 * unconditionally. A production/store release build (the normal
 * `expo prebuild` + `assembleRelease` path a founder or CI would run
 * without setting the env var) gets NO cleartext override at all — same as
 * stock Expo/RN release behavior.
 *
 * `expo-build-properties` was considered first (per the architect's
 * instruction to prefer supported declarative config over a custom
 * plugin) — it only exposes a blanket `android.usesCleartextTraffic`
 * boolean (see its `pluginConfig.ts`), which would permit cleartext to
 * EVERY host in release, not just loopback. That's a strictly worse
 * security posture than the loopback-scoped `network_security_config.xml`
 * this plugin writes, so a custom plugin is used instead.
 */

const QA_ENV_VAR = 'BUXO_QA_CLEARTEXT';

function isQaCleartextEnabled() {
  const value = process.env[QA_ENV_VAR];
  return value === '1' || value === 'true';
}

const NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  QA-only network security config — device-e13 plan (docs/plan-device-e13/00-plan.md, M0).
  Regenerated by apps/mobile/plugins/withQaCleartext.js on every \`expo prebuild\`
  when BUXO_QA_CLEARTEXT=1 (default OFF). See that plugin's docblock for the
  full rationale.

  Purpose: the M2 performance gate must be measured on a release-like build
  (debug/reanimated is dramatically slower and would give a false negative),
  but API 33 blocks cleartext HTTP by default in release, and the release
  build needs to talk to the LOCAL harness (harness/web-local/, BUXO_FAKE_MODELS=1)
  at http://localhost:3001 via \`adb reverse tcp:3001 tcp:3001\`.

  This allows cleartext ONLY to loopback addresses (10.0.2.2 is the Android
  emulator's alias for the host loopback; 127.0.0.1/localhost is the device's
  own loopback, which is what \`adb reverse\` maps to). It does NOT enable
  cleartext globally — any other host still requires HTTPS, same as stock
  release behavior. Scoped to the \`release\` build type only
  (app/src/release/, this file's own source set) — debug/debugOptimized use
  their own manifest's \`usesCleartextTraffic=true\` (RN Gradle plugin
  default, unrelated to this file) and never load this config.

  This file must never ship in a real production release to end users under
  the beta signing key on Render prod. It is only generated when
  BUXO_QA_CLEARTEXT=1 is set for the \`expo prebuild\` invocation — omit that
  env var (the default) for any build meant for students.
-->
<network-security-config>
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">localhost</domain>
    <domain includeSubdomains="false">127.0.0.1</domain>
    <domain includeSubdomains="false">10.0.2.2</domain>
  </domain-config>
</network-security-config>
`;

const RELEASE_MANIFEST_XML = `<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <!--
      QA-only, release build type — device-e13 plan (docs/plan-device-e13/00-plan.md, M0/M2).
      Regenerated by apps/mobile/plugins/withQaCleartext.js on every
      \`expo prebuild\` when BUXO_QA_CLEARTEXT=1 (default OFF).
      Points at app/src/release/res/xml/network_security_config.xml, which
      permits cleartext ONLY to localhost/127.0.0.1/10.0.2.2 (the harness
      server, reached via \`adb reverse tcp:3001 tcp:3001\`). Does NOT set
      usesCleartextTraffic="true" globally — release keeps AGP's default
      (cleartext blocked) for every other host. See that file's docblock for
      the full rationale and the removal note before a real store release.
    -->
    <application android:networkSecurityConfig="@xml/network_security_config" tools:targetApi="28" />
</manifest>
`;

/** @type {import('@expo/config-plugins').ConfigPlugin} */
const withQaCleartext = (config) => {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const appDir = path.join(config.modRequest.platformProjectRoot, 'app');
      const releaseManifestPath = path.join(appDir, 'src', 'release', 'AndroidManifest.xml');
      const networkConfigDir = path.join(appDir, 'src', 'release', 'res', 'xml');
      const networkConfigPath = path.join(networkConfigDir, 'network_security_config.xml');

      if (isQaCleartextEnabled()) {
        await fs.promises.mkdir(path.dirname(releaseManifestPath), { recursive: true });
        await fs.promises.mkdir(networkConfigDir, { recursive: true });
        await fs.promises.writeFile(releaseManifestPath, RELEASE_MANIFEST_XML);
        await fs.promises.writeFile(networkConfigPath, NETWORK_SECURITY_CONFIG_XML);
      } else {
        // Default OFF: make sure no stale QA override survives a non-clean
        // prebuild (e.g. the env var was set in a previous run and is unset
        // now) — a build meant for students must never inherit a leftover
        // cleartext exception.
        await fs.promises.rm(releaseManifestPath, { force: true });
        await fs.promises.rm(networkConfigPath, { force: true });
      }

      return config;
    },
  ]);
};

module.exports = withQaCleartext;
module.exports.isQaCleartextEnabled = isQaCleartextEnabled;
module.exports.QA_ENV_VAR = QA_ENV_VAR;
